### ISSUE TITLE
Failure with "RequestError [HttpError]: fetch failed" when running UI tests

### ISSUE THREAD

**Issue by SmialyKot** [saucelabs/saucectl-run-action#34]
## Expected Behavior
Action does not fail with code 500 or retries automatically when failed to fetch (for example 3 retries with backoff).

## Actual Behavior
Starting UI tests via `saucectl-run-action` fails once per ~15 runs with the following message:
```
/home/github/actions-runner/_work/_actions/saucelabs/saucectl-run-action/v4/dist/main/index.js:7814
    throw new requestError.RequestError(error.message, 500, {
          ^

RequestError [HttpError]: fetch failed
    at /home/github/actions-runner/_work/_actions/saucelabs/saucectl-run-action/v4/dist/main/index.js:7814:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async selectCompatibleVersion (/home/github/actions-runner/_work/_actions/saucelabs/saucectl-run-action/v4/dist/main/index.js:16408:20)
    at async saucectlInstall (/home/github/actions-runner/_work/_actions/saucelabs/saucectl-run-action/v4/dist/main/index.js:16428:19)
    at async run (/home/github/actions-runner/_work/_actions/saucelabs/saucectl-run-action/v4/dist/main/index.js:16763:9) {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/saucelabs/saucectl/releases',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/19.0.4 octokit-core.js/4.0.5 Node.js/20.8.1 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  }
}

Node.js v20.8.1
```
We run the action the following way:
```yaml
      - name: Run tests
        uses: saucelabs/saucectl-run-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

## Steps to Reproduce the Problem

  1. In our case - run multiple jobs (15+) in parallel, at least one will fail with this issue

## Specifications

  - Version: saucectl-run-action@v4
  - Platform: Ubuntu 22.04

**Comment by alexplischke** [comment]
@SmialyKot Do these errors occur around the same time as any of the [GitHub Incidents](https://www.githubstatus.com/history)?

**Comment by SmialyKot** [comment]
Yes, it seems to have been Github outage. Thanks
